# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160811_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='day',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='app.Exercise'),
        ),
        migrations.AlterField(
            model_name='day',
            name='plan',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='app.Plan'),
        ),
    ]
